baseURL = 'https://example.org/'
author = "Jose Ortiz"
copyright = "Copyright Â© 2024, Jose Ortiz; all rights reserved."
paginate = 3
languageCode = 'en-us'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
title = 'Jose Ortiz'
theme = "paper"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'joseortizdev'               # twitter.com/YOUR_TWITTER_ID
  github = 'sudopriestmx'                 # github.com/YOUR_GITHUB_ID
  instagram = 'joseortizdev'           # instagram.com/YOUR_INSTAGRAM_ID
  threads = '@joseortizdev'           # threads.net/@YOUR_THREADS_ID
  linkedin = 'josepabloortizlack'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'https://hachyderm.io/@joseortizdev'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true
  # home page profile
  avatar = 'joseortizlack@outlook.com'                 # gravatar email or image url
  name = '@joseortizdev'
  bio = 'Company Team Leader @Distillery / Senior Back-End Developer-KYC @NaranjaX ğŸŒ Multilingual: ğŸ‡²ğŸ‡½ğŸ‡©ğŸ‡ªğŸ‡ºğŸ‡¸'


  # misc
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally

  # giscus
  [params.giscus]
    repo = 'sudopriestmx/blog'                 # see https://giscus.app for more details
    repoId = 'R_kgDOLz4yyw'
    category = 'Announcements'
    categoryId = 'DIC_kwDOLz4yy84Ce-vj'
    mapping = 'pathname'
    theme = 'dark'
    lang = 'en'

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
     [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
#[markup.highlight]
#  lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true